### ISSUE TITLE
Swap " and '

### ISSUE THREAD

**Issue by contrapunctus-1** [kmonad/kmonad#321] opened 2021-08-02 07:15 UTC
I want to try swapping ' and ", but I was told it's not possible. This is something I'd like to be able to do with Kmonad.

Thanks for this amazing package, I've greatly enjoyed what I could accomplish with it so far. (https://tilde.team/~contrapunctus/blog/keyboard-machinations-kmonad.html)

**Comment by molleweide** [comment] 2021-08-02 08:14
Hmm yeah id like also to swap ; and : also to make ; capitalized.

**Comment by slotThe** [comment] 2021-08-06 09:52
It's certainly _possible_ to do this right now by having an explicit shift layer and just swapping `'` and `"` there (this may or may not mess up Programs that expect chords of the form `M-S-s`, I haven't tested this).  This is, however, not ideal and I agree we ought to do something clever here.

For now, I'm going to close this as a duplicate of #111, where basically the same thing is discussed (to some lengths)

**Closed by slotThe** 2021-08-06 09:52 UTC
