### ISSUE TITLE
Relation to other keyboard remappers

### ISSUE THREAD

**Issue by cjh9** [kmonad/kmonad#250] opened 2021-05-15 22:03 UTC
This project looks really great! I've been trying so hard to find a remapper similar to Karabiner for linux, I think this may be the one.

What is the relation to other similar projects?
https://github.com/autokey/autokey
https://github.com/thkala/evmapd
https://github.com/philipl/evdevremapkeys
https://github.com/snyball/Hawck

And why the name "kmonad", has it anything to do with the tiling window manager xmonad?

**Comment by david-janssen** [comment] 2021-05-16 07:03
I don't know what you mean by 'relation', and I'm not familiar with those 4 other remappers.

I think what we are closest to is actually:
https://qmk.fm/

Except qmk is firmware for mechanical keyboards, and kmonad runs in software. QMK has more features, but can only run on keyboards that have programmable microcontrollers in them. I'm hoping to catch up to QMK's features eventually :-)

"kmonad" was very much a direct wink at "xmonad", which is the window manager I use. They are both written in Haskell, and internally XMonad has an X-monad (monad is a functional programming concept) and we have a K-monad (K, short for Key). No further relation.

**Comment by david-janssen** [comment] 2021-05-16 07:04
Also, closing, because I think I answered the question.

**Closed by david-janssen** 2021-05-16 07:04 UTC

**Comment by cjh9** [comment] 2021-05-16 08:48
@david-janssen I see!
What I mean by relation is can they do similar things, overlapping functionality etc or are they different and have different use-cases? It's ok if you don't know about them, it's just that I have looked on them and was not able to use them...

The to-go remapping is obviously Karabiner for Mac, it works great but the remapping syntax is very tedious to write yourself (big json file). If this could be a remapping that would work across different operating system it would be completely awesome! 

All the current remappings in Linux seemed so caotic having to install several programs using xcape, xmodmap, etc etc so if this could solve all the issues it would be amazing. Otherwise I was planning to do the remapping myself by looking at this example:

https://gist.github.com/t184256/f4994037a2a204774ef3b9a2b38736dc
https://manpages.ubuntu.com/manpages/xenial/man4/evdev.4.html

Are you using evdev/uinput in this project? I couldn't find it by searching...

Or maybe I'm completely wrong and missunderstands the purpose of this project :P

**Comment by david-janssen** [comment] 2021-05-16 08:59
> Are you using evdev/uinput in this project? I couldn't find it by searching...

Yep, we use `ioctl` to grab linux event files, and `uinput` to do linux output. For Mac we use something else that our resident Mac specialist might be able to explain better. We reuse some `kext` from Karabiner actually, I think.

KMonad works independently of X11, so it would even work on the TTY, but it doesn't play nice with non-standard X11 locales, so it's usually easiest to set your locale to US-english, and then put all of your remapping into KMonad. We do support most X11 compose sequences, so special-character support in X11 is actually quite decent.

**Comment by cjh9** [comment] 2021-05-16 16:02
@david-janssen I see, so you mean it will work on tty as if you press Ctrl+Alt+F3 and get the terminal?

So it will work on Wayland then? Aren't most DE-environments transitioning to Wayland soon?

**Comment by vherrmann** [comment] 2021-05-16 16:03
Yes it works for wayland as well.

**Comment by vherrmann** [comment] 2021-05-16 16:08
> All the current remappings in Linux seemed so caotic having to install several programs using xcape, xmodmap, etc etc so if this could solve all the issues it would be amazing. Otherwise I was planning to do the remapping myself by looking at this example:

Sorry to disappoint you, but kmonad won't solve all problems. The first few i know are:
1. Unicode handling. Kmonad doesn't support real unicode on linux (yet?).
2. You won't be able to play games with the same layout, since

**Comment by david-janssen** [comment] 2021-05-16 16:19
> Unicode handling. Kmonad doesn't support real unicode on linux (yet?).

I would love to, but I don't think the kernel has a uniform Unicode insertion method yet, right? There are certain number codes supported by certain programs, and other methods for other programs.

If there was an 'insertUTF8' kernel call, we'd be Unicoding it up in here, but the technology we rely on isn't there yet, so we can't do it either.

> You won't be able to play games with the same layout as intended from the game developers

Oh, I didn't realize that. On Linux it should be fine, right? On Windows I guess a lot of games 'grab' the core keyboard itself, and interfere with our keyboard grab in that way.

> Kmonad is sort of a hack, therefore there isn't necessarily a connection between what an application thinks how you press a shortcut and how you acctually press it.

I like to think that the other applications are the hacks, but I get your point ;).

**Comment by vherrmann** [comment] 2021-05-16 16:19
> All the current remappings in Linux seemed so caotic having to install several programs using xcape, xmodmap, etc etc so if this could solve all the issues it would be amazing. Otherwise I was planning to do the remapping myself by looking at this example:

Btw, xmodmap is outdated, you should use xkb (I don't think xmodmap will work on wayland it contrast to xmodmap).

**Comment by vherrmann** [comment] 2021-05-16 16:22
> I like to think that the other applications are the hacks, but I get your point ;).

Many applications have *bad* keyhandling.

> Oh, I didn't realize that. On Linux it should be fine, right? On Windows I guess a lot of games 'grab' the core keyboard itself, and interfere with our keyboard grab in that way.

What exactly do you mean with interfere, do you mean that those applications bypass kmonad?

**Comment by 6gk** [comment] 2021-05-16 16:26
> What exactly do you mean with interfere, do you mean that those applications bypass kmonad?

Kind of, yeah.

On windows full screen applications tend to get near-exclusive keyboard control.

**Comment by cjh9** [comment] 2021-05-16 16:30
@vherrmann 
1. Unicode, hmm. I don't really know if I need that, what is it usefull for beyond sending emojis etc?
2. Maybe I can disable it when playing games? What do you mean by this? If the regexp filter is implemented in the future it will be done automatically. 
3. I usually have root acess on all my computers so that is ok.
4.  Hmm I don't quite understand this point, could you elaborate a bit more?

The main thing I'd like to accomplish is this, and the others are not super important:
1. **Swap modifiers**, so put super, alt, ctrl in the row. 
2. Put Escape on caps lock
3. Maybe have **dual use on the modifiers**, when pressed alone do something, use as modifier when hold.

And then just remap commands, with **N:N mapping** like>
alt + a => ctrl + left 
alt + s => ctrl + right

Yes I've also heard I should use xkb instead, but can it accomplish this? It looked very complicated. I've developed a program that generates autokey configuration files for all my commands, but they grab the window, and can not use super key since there are a lot of command that is grabbed by gnome before... And autokey can not handle exclude regexp for the program window...

I'm not so concerned about "bleed trough modifiers" different "modes" etc, I just would like to have command => command mapping... And mostly for productivity, I don't play that many games :P So if it works for the os, vscode and chromium it is enough :D

**Comment by cjh9** [comment] 2021-05-16 16:33
And most important a minimalistic way to define the command => command mapping, preferably on one row. Can kmonad accomplish this?

**Comment by vherrmann** [comment] 2021-05-16 16:43
> Unicode, hmm. I don't really know if I need that, what is it usefull for beyond sending emojis etc?

Literally every language, that isn't english, but also for input of mathemtical symbols, ™, ® all that stuff.

> Maybe I can disable it when playing games? What do you mean by this? If the regexp filter is implemented in the future it will be done automatically.

Regex filter?
Also, yes you could make a keybinding in kmonad, that switches to a normal layout

> I usually have root acess on all my computers so that is ok.

If you use a ergonomic layout like me, you want to use your layout as often as possible. (The statement was more generell)

> 4. Hmm I don't quite understand this point, could you elaborate a bit more?

E.g. you rebind `M-a`→ `C-<Left>`. If you create the shortcut `C-<Left>` in for $ACTION in chromium, then chromium will think, that you have to press `C-<Left>` on the keyboard to execute $ACTION and it will show you that in the keyshortcut dialog (i have no idea if chromium has this feature, i'm just assuming it). But that's not what you press on your keyboard.

**Comment by vherrmann** [comment] 2021-05-16 16:44
> 
    Swap modifiers, so put super, alt, ctrl in the row.
    Put Escape on caps lock
    Maybe have dual use on the modifiers, when pressed alone do something, use as modifier when hold.

All of this is possible with kmonad

**Comment by david-janssen** [comment] 2021-05-16 16:44
> What exactly do you mean with interfere, do you mean that those applications bypass kmonad?

In windows we don't get very fine-grained control over what we capture, so it wouldn't surprise me if games manage to get a 'deeper grab' than us, and bypass KMonad. 

> Unicode, hmm. I don't really know if I need that, what is it usefull for beyond sending emojis etc?

Actually, directly inserting things like `?`, (instead of `shifted-/`) would make things a lot easier. Also, it would make it *much* more straightforward to support accents, umlauts, greek or cyrillic, etc. Although, IIRC, Unicode isn't actually an encoding, it's more of a consortium that manages maps right? So UTF-8 would be an actual encoding, and being able to insert UTF-8 directly into the kernl would be great. I heard there's windows support for this, so maybe we'll be adding that there soon.

> If the regexp filter is implemented in the future it will be done automatically.

Not if those applications can perform interfere with our keyboard grab.


> Swap modifiers, so put super, alt, ctrl in the row.
> Put Escape on caps lock
> Maybe have dual use on the modifiers, when pressed alone do something, use as modifier when hold.

Also super easy and supported. Check the `./keymap/tutorial.kbd` for a full overview of features.

> And then just remap commands, with N:N mapping like>
> alt + a => ctrl + left
> alt + s => ctrl + right

That syntax (command->command) mapping is not supported, but you could easily define a layer that you access by `alt` where `a` is bound to `ctrl-left` and `s` is bound to `ctrl-right`. So the semantics are supported.

**Comment by vherrmann** [comment] 2021-05-16 16:45
> Yes I've also heard I should use xkb instead, but can it accomplish this? It looked very complicated. I've developed a program that generates autokey configuration files for all my commands, but they grab the window, and can not use super key since there are a lot of command that is grabbed by gnome before... And autokey can not handle exclude regexp for the program window...

xkb is made for keyboard layouts. So it's very hard to do it yourself. Btw I think there is an option for turning esc on capslock on.

**Comment by vherrmann** [comment] 2021-05-16 16:53
> Oh, I didn't realize that. On Linux it should be fine, right? On Windows I guess a lot of games 'grab' the core keyboard itself, and interfere with our keyboard grab in that way.

Well, in fact i want that games differentiate between „game controls“ and „text input“. I want that „game controls“ depend on the position and „text input“ on the keyboard layout. So if i create my custom kb layout in kmonad for „text input“, the „game controls“ won't work like intended. The only game i know, which does this pretty well is the current version of Minecraft (has still some issues).

**Comment by vherrmann** [comment] 2021-05-16 17:00
> I would love to, but I don't think the kernel has a uniform Unicode insertion method yet, right? There are certain number codes supported by certain programs, and other methods for other programs.

Which programs do you have in mind?
Because it seems like i can input a part of unicode on the TTY

**Comment by david-janssen** [comment] 2021-05-16 17:11
Yeah, the TTY has numerical insert methods. Then I think Gnome supports a different set of combinations. I remember looking into this like... a year ago. And then going: toooo much bother.

**Comment by cjh9** [comment] 2021-05-16 18:52
@vherrmann 

> Literally every language, that isn't english, but also for input of mathemtical symbols, ™, ® all that stuff.

Yes, true. Actually I may need it since I'd like to output åäö with a command.
  
> Regex filter?
> Also, yes you could make a keybinding in kmonad, that switches to a normal layout
Both Karabiner and Autokey have regexp filters, so for example run (or don't run) a remapping when you are using a window that matches terminal.* 
 
> If you use a ergonomic layout like me, you want to use your layout as often as possible. (The statement was more generell)
You mean you use Dvorak or Colemak or something like that?
 

> E.g. you rebind `M-a`→ `C-<Left>`. If you create the shortcut `C-<Left>` in for $ACTION in chromium, then chromium will think, that you have to press `C-<Left>` on the keyboard to execute $ACTION and it will show you that in the keyshortcut dialog (i have no idea if chromium has this feature, i'm just assuming it). But that's not what you press on your keyboard.

This is completely fine for me, since I will take into consideration what shortcuts chromium have by default. So the idea is to use default hotkeys for all applications but use my special remapping, for example switch tabs:
map alt to control
alt => ctrl
ctrl + 2 => ctrl + PgUp
ctrl + 3 => ctrl + PgDown

**Comment by cjh9** [comment] 2021-05-16 18:56
@vherrmann 

> > Swap modifiers, so put super, alt, ctrl in the row.
> > Put Escape on caps lock
> > Maybe have dual use on the modifiers, when pressed alone do something, use as modifier when hold.
> 
> All of this is possible with kmonad

I see but not the command => command functionality?

**Comment by cjh9** [comment] 2021-05-16 19:03
@david-janssen 

> > And then just remap commands, with N:N mapping like>
> > alt + a => ctrl + left
> > alt + s => ctrl + right
> 
> That syntax (command->command) mapping is not supported, but you could easily define a layer that you access by `alt` where `a` is bound to `ctrl-left` and `s` is bound to `ctrl-right`. So the semantics are supported.

Oh I see, great! I'll take a look at the documentation better. The command => command is the most important for me. 

Or, more correctly, first remap modifier then use the new modifier positions to remap command => command.

**Comment by molleweide** [comment] 2021-05-16 19:09
@cjh9 you can check out #227 that also talks about combos

**Comment by cjh9** [comment] 2021-05-16 19:22
@molleweide
> @cjh9 you can check out #227 that also talks about combos
Aww right! Hmm it is not possible to send commands, or several commands. That is kind of important... Perhaps I have to use autokey instead... :/ Or, maybe xdotool, for example: xdotool key ctrl+a

**Comment by molleweide** [comment] 2021-05-16 19:28
> Can you run a bash script on key command?

yes.

also the combo keys feature is in the pipe but not with a set timeline. I cannot comment any further because I'm only learning haskell atm.

**Comment by cjh9** [comment] 2021-05-16 19:31
> > Can you run a bash script on key command?
> 
> yes.
> 
> also the combo keys feature is in the pipe but not with a set timeline. I cannot comment any further because I'm only learning haskell atm.

@molleweide I see, but in that case I think everything is covered. I could use xdotool unitll the combo tool and regex filters are implemented.

**Comment by vherrmann** [comment] 2021-05-16 19:38
What do you mean with commands? Kmonad buttons? It is very well possible to bind multiple buttons to one key.

**Comment by molleweide** [comment] 2021-05-16 19:42
yeah you should skim through keymaps/tutorial.kbd. things will become more clear then.

**Comment by vherrmann** [comment] 2021-05-16 19:46
@cjh9 
> You mean you use Dvorak or Colemak or something like that?

I use [bone](https://neo-layout.org/Layouts/bone/).

> Both Karabiner and Autokey have regexp filters, so for example run (or don't run) a remapping when you are using a window that matches terminal.*

I don't think such a feature is planned for kmonad. But i think you could implement such a behaviour with an extern program.

> Yes, true. Actually I may need it since I'd like to output åäö with a command.

Well, i didn't said there was no support for unicode, the problem is just, that it is a hack and not very extensible. (at least ä, ö should work out of the box)

**Comment by cjh9** [comment] 2021-05-16 21:00
> > Aww right! Hmm it is not possible to send commands, or several commands.
> 
> What do you mean with commands? Kmonad buttons? It is very well possible to bind multiple buttons to one key.

So for example, I'm creating a webb app. I want alt + r to save all files,  switch window from vscode to the broswer and refresh the browser.
Then I want:
alt + r =>
ctrl + shift + s,
alt + tab,
ctrl + r

I can do things like this in karabiner for mac and autokey for linux.. I could perhaps create a script with multiple xdotool commands and run it with kmonad.

**Comment by cjh9** [comment] 2021-05-16 21:01
@molleweide 

> yeah you should skim through keymaps/tutorial.kbd. things will become more clear then.

Sure, will do!

**Comment by vherrmann** [comment] 2021-05-16 21:03
> I can do things like this in karabiner for mac and autokey for linux.. I could perhaps create a script with multiple xdotool commands and run it with kmonad.

This is even without xdotool possible with kmonad

**Comment by cjh9** [comment] 2021-05-16 21:05
@vherrmann 

> 
> > You mean you use Dvorak or Colemak or something like that?
> 
> I use [bone](https://neo-layout.org/Layouts/bone/).
>

Cool! Will check out, only german as of now?


> > Both Karabiner and Autokey have regexp filters, so for example run (or don't run) a remapping when you are using a window that matches terminal.*
> 
> I don't think such a feature is planned for kmonad. But i think you could implement such a behaviour with an extern program.

What about this issue? https://github.com/kmonad/kmonad/issues/136

> > Yes, true. Actually I may need it since I'd like to output åäö with a command.
> 
> Well, i didn't said there was no support for unicode, the problem is just, that it is a hack and not very extensible. (at least ä, ö should work out of the box)

I see, sounds great! I need å though, kind of important in my language :P

**Comment by cjh9** [comment] 2021-05-16 21:07
@vherrmann 

> > I can do things like this in karabiner for mac and autokey for linux.. I could perhaps create a script with multiple xdotool commands and run it with kmonad.
> 
> This is even without xdotool possible with kmonad

Perfect!

**Comment by vherrmann** [comment] 2021-05-16 21:27
> I see, sounds great! I need å though, kind of important in my language :P

I never said å is not implemented, i just don't know if it is.

> What about this issue? #136

I can imagine, kmonad having some sort of signal as input, but i don't think kmonad will ever have application specific handling ever built-in, because this would add more platforms (this would split the platform „linux“ into X and Wayland/All Wayland compositors) and i also think, that for each individiual plaltform, this would be a huge task. Apart from that, imho such a feature wouldn't fit into kmonad, from an unix philosophy standpoint. 

In contrast, if the signal mechanism was implemented, a program could be written (at least for X), which notifies wayland if the window changes.

> Cool! Will check out, only german as of now?

Yes there are some similar layouts, that take english into account and there is also [this](https://github.com/jackrosenthal/threelayout) for pure english.

**Comment by cjh9** [comment] 2021-05-17 08:57
> > I see, sounds great! I need å though, kind of important in my language :P
> 
> I never said å is not implemented, i just don't know if it is.

I see :)

> 
> > What about this issue? #136
> 
> I can imagine, kmonad having some sort of signal as input, but i don't think kmonad will ever have application specific handling ever built-in, because this would add more platforms (this would split the platform „linux“ into X and Wayland/All Wayland compositors) and i also think, that for each individiual plaltform, this would be a huge task. Apart from that, imho such a feature wouldn't fit into kmonad, from an unix philosophy standpoint.
> 
> In contrast, if the signal mechanism was implemented, a program could be written (at least for X), which notifies wayland if the window changes.
> 

I understand, hmm, this is kind of important, maybe have to resort to autokey or something like tat.


> > Cool! Will check out, only german as of now?
> 
> Yes there are some similar layouts, that take english into account and there is also [this](https://github.com/jackrosenthal/threelayout) for pure english.

Looks like a great layout! It uses Karabiner for mac. Do you think it's better to use kmonad only for ergonomic layout or setxkbmap + kmonad?

**Comment by vherrmann** [comment] 2021-05-17 09:12
> I understand, hmm, this is kind of important, maybe have to resort to autokey or something like tat.

It's already sort of possible, because you can restart kmonad with a different file, when you focus another application. (Although this would be a pain to configure for complex layouts)

> Looks like a great layout! It uses Karabiner for mac. Do you think it's better to use kmonad only for ergonomic layout or setxkbmap + kmonad?

I guess you talk about linux, because setxkbmap is only usable on X. I don't think kmonad has enough features to implement neo or one of its derivatives (bone/3l/vou/koy/adnw) easily and completely ( you might want to take a look at @MaxGyver83 configs in the directory keymap/user/MaxGyver83). Though you might not need all of its features.

**Comment by cjh9** [comment] 2021-05-17 10:00
@vherrmann Hmm I see, yes I mean for Linux. Oh, too bad :/ I really like to use as few tools as possible for the keyboard remapping.. Yes, I'll take a look!
