### ISSUE TITLE
How to make kmonad repeat a cmd-button while pressing a key

### ISSUE THREAD

**Issue by taquangtrung** [kmonad/kmonad#394] opened 2021-11-05 03:06 UTC
Hi,

I'm using the `cmd-button` feature to run a script that moves windows in Linux.

Here is my configuration:

```emacs
(defcfg
  ;; input  (device-file "/dev/input/by-id/usb-04d9_USB-HID_Keyboard-event-kbd")
  input  (device-file "/dev/input/by-id/usb-04d9_USB-HID_Keyboard-event-kbd")
  output (uinput-sink "KMonad kbd")

  cmp-seq-delay 5

  fallthrough true ;; Allow unhandled events to be emitted
  allow-cmd true   ;; Allow command-execution in KMonad
  )
  
(defalias
  ems (layer-toggle emacs)
  ml (cmd-button "configure-window.sh move-left")
  mr (cmd-button "configure-window.sh move-right")
  )  
```

Where I assign `@ems` to `CAPS` and `ml` (move-left), `mr` (move-right) to `CAPS` + `[`, `CAPS` + `]`.

It can work well to move a window to the left if I press `CAPS` + `[` and release `]`.

However, when holding both `CAPS` + `[`, the window only moves once, and will not continue to move.

It is possible to make KMonad repeat a command when a key is held?

Thank you for taking a look at my question.

**Comment by MuhammedZakir** [comment] 2021-11-05 16:25
Duplicate of #286. A solution is posted there<sup>[1]</sup> - wrape what you want to repeat in an infinite loop in the command for `press` and kill it in the command for `release`.

```clojure
;; (cmd-button "<cmd for press>" "<cmd for release>")
(cmd-button "whilte true; do configure-window.sh move-left && sleep 0.3; done"
       "ps ax | grep \'configure-window.sh move-left\' | head -1 | awk \'{print $1}\' | xargs kill") 
```

[1] https://github.com/kmonad/kmonad/issues/286#issuecomment-898534625

**Comment by taquangtrung** [comment] 2021-11-05 16:42
Thank you very much for the tips! I wasn't aware of this issue, but this is a valid workaround.

I just tested and see that using the `while` loop, the repeating speed is a bit slower than when I manually press the key up and down continuously. 

Not sure why it is so, I'm trying to figure it out.

**Comment by MuhammedZakir** [comment] 2021-11-05 16:44
> Thank you very much for the tips! I wasn't aware of this issue, but this is a valid workaround.

You're welcome! :-)

> I just tested and see that using the `while` loop, the repeating speed is a bit slower than when I manually press the key up and down continuously.
> 
> Not sure why it is so, I'm trying to figure it out.

Try adjusting the time for `sleep`?

**Comment by taquangtrung** [comment] 2021-11-05 16:46
Yes, I removed the sleep command, and it is still slower like 2, 3 times compared to when I manually press.

**Comment by MuhammedZakir** [comment] 2021-11-05 16:50
Another method is to convert whatever is in `configure-window.sh` to function(s), then source that script before loop, and call the "main" function. This may not increase execution speed if shell optimizes the code I posted above.
 j
```
"source /path/to/configure-window..sh; while true; do configure-window move-left && sleep 0.2; done"
```

**Comment by taquangtrung** [comment] 2021-11-05 17:07
Oh I see. That's could be the reason. I'll try to see how to improve it. Thanks a lot for the tip! :)

**Comment by slotThe** [comment] 2021-11-14 11:36
@taquangtrung did this solve your issue?

**Comment by taquangtrung** [comment] 2021-11-14 13:56
@slotThe: somehow using the `while` loop in a shell script still makes the execution very slow.

I ended up making a system binding the command `configure-window.sh move-left` to the key combination `Control + Shift + Meta + Super + [`, and then use KMonad to bind `CAPS + [` to that key combination. Then, there's no delay in the execution.

**Closed** 2021-11-17 09:04 UTC
