### ISSUE TITLE
Deflayer without having to redeclared whole defsrc? 

### ISSUE THREAD

**Issue by AndreyAdrian** [kmonad/kmonad#750] opened 2023-10-16 06:25 UTC
If just want to make a 1 change in one layer, do i have to put all those _?

```
(deflayer modded-test
  _    _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    @m1  _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _    _    _
  _    _    _    _    _    _    _    _    _    _    _
  _    _    _              _              _    _    _    _
)
```

------
What about if defsrc is like this: 

```
(defsrc
  grv   1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab   q    w    e    r    t    y    u    i    o    p    [    ]    ret
  caps  a    s    d    f    g    h    j    k    l    ;    '    \
  lsft lsgt  z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt            spc                 ralt rmet cmp  rctl
)
```
Do something like:
```
(deflayer qwerty
  w=@m1
)
```

**Comment by slotThe** [comment] 2023-10-16 18:03
As of right now yes, you have to declare the whole `deflayer` if you're declaring a full `defsrc`. However, I don't think it would be terribly difficult to hack this into the `deflayer` parsing (though I guess this would be a one-way street—as soon as such an assignment is found, every key in the `deflayer` should be one)

**Comment by AndreyAdrian** [comment] 2023-10-16 18:20
Oh I see, well basically I was asking because Im trying to achieve the adaptative key/magic key/alternate repeat key/... behaviour.
Is there a built-in function for that? 
Is this approach of putting layers on top to replace 1 key a good approach?

I will create an issue briefly to try to explain it better if someone else is also looking to achieve the same behaviour.

**Comment by AndreyAdrian** [comment] 2023-10-16 18:32
> Oh I see, well basically I was asking because Im trying to achieve the adaptative key/magic key/alternate repeat key/... behaviour. Is there a built-in function for that? Is this approach of putting layers on top to replace 1 key a good approach?
> 
> I will create an issue briefly to try to explain it better if someone else is also looking to achieve the same behaviour.

#751

**Comment by slotThe** [comment] 2023-10-16 19:05
Closing as duplicate of https://github.com/kmonad/kmonad/issues/680

**Closed by slotThe** 2023-10-16 19:05 UTC
