### ISSUE TITLE
Custom Key Creation

### ISSUE THREAD

**Issue by austinliuigi** [kmonad/kmonad#352] opened 2021-09-10 08:45 UTC
I'm not entirely sure if this is possible or if there is a current workaround to do this, but I was thinking that a cool feature could be the ability to create a custom key. For example, one could define a key named "mykey" that acts as `a` when pressed, `$` when pressed with `shift`, and `esc` when pressed with `control`.

**Comment by Ultrahalf** [comment] 2021-09-16 12:24
#313 sounds similar

**Comment by slotThe** [comment] 2021-09-16 12:58
Indeed this basically sounds like #157, just specified to shift and caps; @austinliuigi is that what you meant?

**Comment by austinliuigi** [comment] 2021-09-17 19:41
> Indeed this basically sounds like #157, just specified to shift and caps; @austinliuigi is that what you meant?

That’s pretty much what I meant. If #157 gets implemented, then it will cover this issue as well.

**Comment by david-janssen** [comment] 2021-09-17 20:23
> That’s pretty much what I meant. If #157 gets implemented, then it will cover this issue as well.

Very good :-) In that case: closing for reasons of duplication.

**Closed by david-janssen** 2021-09-17 20:23 UTC

**Comment by david-janssen** [comment] 2021-09-17 20:24
Apparently I can officially mark it as such by saying:

Duplicate of: #157

**Comment by david-janssen** [comment] 2021-09-17 20:25
Duplicate of #157
