### ISSUE TITLE
tap-hold buttons may not work combined with other modifiers in some scenario

### ISSUE THREAD

**Issue by adegorre** [kmonad/kmonad#307] opened 2021-07-08 11:53 UTC
## Bug description

Consider the following scenario:

- using a typical home row mods config with for instance `(tap-hold-next-release 200 f lctl)` on physical key F
- you want to write an uppercase "F"
- you do press rsft, press F, release rsft, release F
- if key F was just a simple F button, this would give expected result
- but if F was this tap-hold button, then only a lowercase "f" will be written (when you release key F), instead of uppercase "F"

With the semantics of tap-hold this is perfectly understandable: kmonad sends the event "tap f" only when key F is released. Unfortunately, this breaks the typing flow.

## A fix?

Suggested fix: if any key release event is caught during the tap-hold delay, then the tap-hold should select the tap behavior.

This would be dual to what already happens on a key press event (in which case the hold behavior is selected).

Remark that if both rules are implemented and tap is selected because of a release of another key K1, this means the press of K1 happened before pressing the tap-hold key K2, so the intent was most likely not to have K1 modified by K2 but the opposite.

But maybe the intent was to have a third key K3 modified both by K1 and K2 (in hold mode), but in this case, you would not release K1 before pressing K3, hence K2 would have already switched to hold mode.

Do I miss another scenario where the suggested fix might actually do something bad?

**Comment by Vermoot** [comment] 2021-07-08 12:27
I had never noticed this behaviour, but I just tested it and you're right! This might explain how often I type a lowercase `i` when trying to type `I`.

This should be addressed for sure!

**Comment by adegorre** [comment] 2021-07-08 22:26
So I tried these changes:

```diff
diff --git a/src/KMonad/Model/Button.hs b/src/KMonad/Model/Button.hs
index 95e08a6..d5497e9 100644
--- a/src/KMonad/Model/Button.hs
+++ b/src/KMonad/Model/Button.hs
@@ -309,7 +309,9 @@ tapHoldNextRelease ms t h = onPress $ do
         -- If the next event is my own release: act like tapped
         | p e -> onRelSelf
         -- If the next event is another release that was pressed after me
-        | isRel && (e^.keycode `elem` ks) -> onRelOther e
+        | isRel && (e^.keycode `elem` ks) -> onRelOtherSeen e
+        -- If the next event is another release that was pressed before me
+        | isRel && (e ^. keycode `notElem` ks) -> onRelOtherUnseen e
         -- If the next event is a press, store and recurse
         | not isRel -> go (ms' - r^.elapsed) (e^.keycode : ks) *> pure NoCatch
         -- If the next event is a release of some button pressed before me, recurse
@@ -321,8 +323,11 @@ tapHoldNextRelease ms t h = onPress $ do
     onRelSelf :: MonadK m => m Catch
     onRelSelf = tap t *> hold False *> pure Catch
 
-    onRelOther :: MonadK m => KeyEvent -> m Catch
-    onRelOther e = press h *> hold False *> inject e *> pure Catch
+    onRelOtherSeen :: MonadK m => KeyEvent -> m Catch
+    onRelOtherSeen e = press h *> hold False *> inject e *> pure Catch
+
+    onRelOtherUnseen :: MonadK m => KeyEvent -> m Catch
+    onRelOtherUnseen e = tap t *> hold False *> inject e *> pure Catch -- tap t *> hold False *> inject e *> pure Catch
 
 
 -- | Create a 'Button' that contains a number of delays and 'Button's. As long
```

But that does not work. For some reason foreign release events don't seem to trigger the tap-hold hook. I also observed a similar issue while working on PR #305 (where I wanted both foreign press and release events to end a multi-tap sequence: only the press event would have the desired effect).

**Comment by adegorre** [comment] 2021-07-08 22:53
So I tried this change:

```diff
diff --git a/src/KMonad/Model/Button.hs b/src/KMonad/Model/Button.hs
index 95e08a6..43afc46 100644
--- a/src/KMonad/Model/Button.hs
+++ b/src/KMonad/Model/Button.hs
@@ -312,8 +312,8 @@ tapHoldNextRelease ms t h = onPress $ do
         | isRel && (e^.keycode `elem` ks) -> onRelOther e
         -- If the next event is a press, store and recurse
         | not isRel -> go (ms' - r^.elapsed) (e^.keycode : ks) *> pure NoCatch
-        -- If the next event is a release of some button pressed before me, recurse
-        | otherwise -> go (ms' - r^.elapsed) ks *> pure NoCatch
+        -- If the next event is a release of some button pressed before me, -recurse- -> no, choose tap!
+        | otherwise -> tap t *> hold False *> pure NoCatch
 
     onTimeout :: MonadK m =>  m ()
     onTimeout = press h *> hold False
```

But that does not work. For some reason foreign release events don't seem to trigger the tap-hold hook. I also observed a similar issue while working on PR #305 (where I wanted both foreign press and release events to end a multi-tap sequence: only the press event would have the desired effect).

**Comment by adegorre** [comment] 2021-07-09 10:29
Another thought: while I don't understand all what is going on here, I acknowledge that the current behavior with respect to modifiers could actually not be a bug but the intended effect when the other modifier is also a dual-key.
Indeed, when you perform a roll on the home-row, the last thing you want is to trigger an unintended ctrl+alt+letter sequence.

So maybe the "bug" I described is only a bug in the corner case where you want to mix home row mods with dedicated mods. On the other hand, when using home row mods only, it is a given that one has to be careful with the release order (both shift+letter and letter+letter are likely intents during a sequence of fast typing; since timing criteria are not a solution when we want speed, their remains only the order of the releases to distinguish both intents).

Let's review the possible orders. Suppose (D, lsft) (F, lctl) are 2 dual keys:
- sequence 1: press D, release D,press F, release F -> desired outcome "df" (current outcome if D is any tap(-hold)(-next)(-release))
- sequence 2: press D, press F, release F, release D -> desired outcome "F" (current outcome if D is any tap(-hold)(-next)(-release) family)
- sequence 3: press D, press F, release D, release F -> desired outcome ??? (if D is tap(-hold)-next, this gives "F", while if it is tap(-hold)-next-release then this gives "df")

If we "fix" #307, then the outcome of sequence 3 would be "F" for all variants, when F is itself a dual key. Indeed: F would resolve to a tap and send its release event to D, who retro-actively would resolve to a mod (ok, when said like this i am starting to see why it could be hard to implement... ). I don't know if this makes sense, I need to think more about the implications.

Disregarding the feasibility of all this, once again, there are times you want sequence 3 to give "F" and times you want it to give "df". I am afraid there cannot be a fully satisfying behavior for this!

**Comment by adegorre** [comment] 2021-07-09 10:37
For the sake of completeness if we take previous example, if key D is just a simple lsft, then current outcomes are 1: 
- sequence 1 -> "f" (ok!)
- sequence 2 -> "F" (ok!)
- sequence 3 -> "f" when F is a tap(-hold)-next-release (definitely not ok, as far as I am concerned! This is inconsistent with the case where F would be a regular alphabetical key)

**Comment by adegorre** [comment] 2021-07-16 09:57
>     * sequence 3: press D, press F, release D, release F -> desired outcome ??? (if D is tap(-hold)-next, this gives "F", while if it is tap(-hold)-next-release then this gives "df")

Sorry, being new to the project (and to the concept of home row mods), I missed something in the documentation: in the case above, the `-release` part of the button name precisely means that releases of buttons pressed before the dual-key was pressed are supposed to be ignored.

So current behavior is completely conform to the specification and to (some) user wishes.

Nonetheless I still think the corner case where the key pressed before the `tap-hold-next-release` button was a (regular) modifier is worth addressing. In particular when you are transitioning from a traditional layout to a pure home row mod based layout and you still have regular mods.

So basically, in this case, we need a way to tell the difference between a modifier release and a regular key release.
I came up with a solution which I don't like (it happens to work but it makes the behavior very non-obvious to guess from the code, so it is bound to be very fragile), consisting in introducing a new kind of button: `strong-mod` (a shift key that tips tap-hold-next-release toward a tap should be configured as `(strong-mod 200 lsft)` instead of just `lsft`), which defers its own release to make sure:
1 - the release input event is seen by `tap-hold-next-release`
2 - the output release is emitted after the `tap-hold-next-release` outputs its tap

This could be done with a patch along these lines:

```diff
diff --git a/src/KMonad/App/Parser/TokenJoiner.hs b/src/KMonad/App/Parser/TokenJoiner.hs
index ff2bd5a..2e44098 100644
--- a/src/KMonad/App/Parser/TokenJoiner.hs
+++ b/src/KMonad/App/Parser/TokenJoiner.hs
@@ -367,6 +367,7 @@ joinButton ns als =
     KMultiTap bs d     -> jst $ multiTap <$> go d <*> mapM f bs
       where f (ms, b) = (fi ms,) <$> go b
     KStickyKey s d     -> jst $ stickyKey (fi s) <$> go d
+    KStrongMod s d     -> jst $ strongMod (fi s) <$> go d
 
     -- Non-action buttons
     KTrans -> pure Nothing
diff --git a/src/KMonad/App/Parser/Tokenizer.hs b/src/KMonad/App/Parser/Tokenizer.hs
index 3d4660f..ac88a0f 100644
--- a/src/KMonad/App/Parser/Tokenizer.hs
+++ b/src/KMonad/App/Parser/Tokenizer.hs
@@ -280,7 +280,8 @@ keywordButtons =
   , ("cmd-button"     , KCommand     <$> lexeme textP <*> optional (lexeme textP))
   , ("pause"          , KPause . fromIntegral <$> numP)
   , ("sticky-key"     , KStickyKey   <$> lexeme numP <*> buttonP)
-  ]
+  , ("strong-mod"     , KStrongMod   <$> lexeme numP <*> buttonP)
+  ]                                                                     
  where
   timed :: Parser [(Int, DefButton)]
   timed = many ((,) <$> lexeme numP <*> lexeme buttonP)
diff --git a/src/KMonad/App/Parser/Types.hs b/src/KMonad/App/Parser/Types.hs
index 69a4257..a1d6c7b 100644
--- a/src/KMonad/App/Parser/Types.hs
+++ b/src/KMonad/App/Parser/Types.hs
@@ -96,6 +96,7 @@ data DefButton
   | KCommand Text (Maybe Text)             -- ^ Execute a shell command on press, as well
                                            --   as possibly on release
   | KStickyKey Int DefButton               -- ^ Act as if a button is pressed for a period of time
+  | KStrongMod Int DefButton               -- ^ Delays the release of the button to either next event or timeout
   | KTrans                                 -- ^ Transparent button that does nothing
   | KBlock                                 -- ^ Button that catches event
   deriving Show
diff --git a/src/KMonad/Args/Joiner.hs b/src/KMonad/Args/Joiner.hs
index 4556d5b..16d5355 100644
--- a/src/KMonad/Args/Joiner.hs
+++ b/src/KMonad/Args/Joiner.hs
@@ -379,6 +379,7 @@ joinButton ns als =
     KMultiTap bs d     -> jst $ multiTap <$> go d <*> mapM f bs
       where f (ms, b) = (fi ms,) <$> go b
     KStickyKey s d     -> jst $ stickyKey (fi s) <$> go d
+    KStrongMod s d     -> jst $ strongMod (fi s) <$> go d
 
     -- Non-action buttons
     KTrans -> pure Nothing
diff --git a/src/KMonad/Args/Parser.hs b/src/KMonad/Args/Parser.hs
index a143a07..c3b6ba2 100644
--- a/src/KMonad/Args/Parser.hs
+++ b/src/KMonad/Args/Parser.hs
@@ -287,6 +287,7 @@ keywordButtons =
   , ("cmd-button"     , KCommand     <$> lexeme textP <*> optional (lexeme textP))
   , ("pause"          , KPause . fromIntegral <$> numP)
   , ("sticky-key"     , KStickyKey   <$> lexeme numP <*> buttonP)
+  , ("strong-mod"     , KStrongMod   <$> lexeme numP <*> buttonP)
   ]
  where
   timed :: Parser [(Int, DefButton)]
diff --git a/src/KMonad/Args/Types.hs b/src/KMonad/Args/Types.hs
index ca5aa57..3777538 100644
--- a/src/KMonad/Args/Types.hs
+++ b/src/KMonad/Args/Types.hs
@@ -102,6 +102,7 @@ data DefButton
   | KCommand Text (Maybe Text)             -- ^ Execute a shell command on press, as well
                                            --   as possibly on release
   | KStickyKey Int DefButton               -- ^ Act as if a button is pressed for a period of time
+  | KStrongMod Int DefButton               -- ^ Delays the release of the button to either next event or timeout
   | KTrans                                 -- ^ Transparent button that does nothing
   | KBlock                                 -- ^ Button that catches event
   deriving Show
diff --git a/src/KMonad/Model/Button.hs b/src/KMonad/Model/Button.hs
index 8cc9bcb..034988d 100644
--- a/src/KMonad/Model/Button.hs
+++ b/src/KMonad/Model/Button.hs
@@ -26,6 +26,7 @@ module KMonad.Model.Button
   -- * Simple buttons
   -- $simple
   , emitB
+  , strongMod
   , modded
   , layerToggle
   , layerSwitch
@@ -308,12 +309,11 @@ tapHoldNextRelease ms t h = onPress $ do
       if
         -- If the next event is my own release: act like tapped
         | p e -> onRelSelf
-        -- If the next event is another release that was pressed after me
-        | isRel && (e^.keycode `elem` ks) -> onRelOther e
+        -- If the next event is another release: if it was pressed after me, switch to hold mode;
+        -- if it was pressed before me, switch to tap mode (remark: this case is not be triggered by other tap-hold buttons)
+        | isRel -> if e^.keycode `elem` ks then onRelOtherPressedAfterMe e else onRelOtherPressedBeforeMe                      
         -- If the next event is a press, store and recurse
-        | not isRel -> go (ms' - r^.elapsed) (e^.keycode : ks) *> pure NoCatch
-        -- If the next event is a release of some button pressed before me, recurse
-        | otherwise -> go (ms' - r^.elapsed) ks *> pure NoCatch
+        | otherwise {- not isRel -} -> go (ms' - r^.elapsed) (e^.keycode : ks) *> pure NoCatch
 
     onTimeout :: MonadK m =>  m ()
     onTimeout = press h *> hold False
@@ -321,8 +321,11 @@ tapHoldNextRelease ms t h = onPress $ do
     onRelSelf :: MonadK m => m Catch
     onRelSelf = tap t *> hold False *> pure Catch
 
-    onRelOther :: MonadK m => KeyEvent -> m Catch
-    onRelOther e = press h *> hold False *> inject e *> pure Catch
+    onRelOtherPressedAfterMe :: MonadK m => KeyEvent -> m Catch
+    onRelOtherPressedAfterMe e = press h *> hold False *> inject e *> pure Catch
+
+    onRelOtherPressedBeforeMe :: MonadK m => m Catch
+    onRelOtherPressedBeforeMe = tap t *> hold False *> pure NoCatch
 
 
 -- | Create a 'Button' that contains a number of delays and 'Button's. As long
@@ -417,3 +418,20 @@ stickyKey ms b = onPress $ go
                *> inject (t^.event)
                *> after 3 (runAction $ b^.releaseAction)
                $> Catch)
+
+-- | A button acting like its argument, except that the argument release is 
+-- postponed until either something else happens or the timeout runs out.
+-- Purpose: use it for modifiers so that they work in a roll with buttons
+-- having a delay (such as multi-tap and tap-hold-next-release).
+strongMod :: Milliseconds  -> Button -> Button
+strongMod ms b =
+  mkButton 
+  (do
+    runAction $ b^.pressAction)
+  (do
+      tHookF InputHook ms (do runAction $ b^.releaseAction)
+        (\_ -> do
+          whenDone (do runAction $ b^.releaseAction)
+          pure NoCatch)
+      )
+
```

(the difference between `tap-hold-next` and `tap-hold-next-release` becomes very thin... I need to research further to make sure there is still one!)

**Comment by whitbur** [comment] 2021-08-04 05:56
I don't think this bug is all that complicated. Any multi-use button selecting the tap behavior for any reason should tap using the mods present when that button was first pressed, not the mods present when it was released or became a tap. Using `(tap-hold-next-release 200 x lsft)` for foo/esc as in the tutorial:

```
Pa Pesc Ra Resc -> ax (correct)
Pesc Pa Resc Ra -> xa (correct)
Plsft Pesc Rlsft Resc -> x (bug, should be X instead, as lsft is a passthrough mod)
Pesc Plsft Resc Rlsft -> x (correct, mods present on release should not be applied)
Pesc 300 Pa Resc Ra -> a or A (bug or correct, see below)
```

The last example works (produces "A") when `a` is not a multi-use button itself, but is bugged when `a` is multi-use for the same reason. As a multi-use button, `a` should recognize the held `esc` as a modifier present when it was first pressed and upgrade its release to "A".

I've tested this on the Moonlander -- it's properly implemented in QMK.

**Comment by whitbur** [comment] 2021-08-04 16:13
Going over the other issues, I can see that this same problem was brought up in #111 and later in #256. **This should probably be resolved as a duplicate**, as some productive discussion has been going on there for a while.

**Comment by dlip** [comment] 2022-03-11 06:43
Is this a duplicate of #272 also?

**Comment by slotThe** [comment] 2022-03-24 16:50
I would imagine, yes

**Closed by slotThe** 2022-03-24 16:50 UTC
