### ISSUE TITLE
sticky-key in kmonad does not work 

### ISSUE THREAD

**Issue by zim0369** [kmonad/kmonad#414] opened 2021-11-14 08:45 UTC
```
> kmonad -d ~/.kmonad.kbd
kmonad: Parse error at 37:6:
   |
37 | ssf (sticky-key lsft)
   |      ^
Unrecognized compose-char

~
```

**Comment by slotThe** [comment] 2021-11-14 09:20
Closed as a duplicate of #409

**Closed by slotThe** 2021-11-14 09:20 UTC
