### ISSUE TITLE
Keyboard + Mouse combination not working if remapped

### ISSUE THREAD

**Issue by glyh** [kmonad/kmonad#492] opened 2022-02-26 14:00 UTC
I've remapped Caps to Shift when hold, Esc when release. I expect holding the key and middle mouse wheel would be treated as shift+ middle mouse(Which is a hot key in Blender), but it won't work. I guess Kmonad only take care of keys but not mouse inputs?

**Comment by slotThe** [comment] 2022-02-27 06:40
On Sat, Feb 26 2022 06:00, ***@***.*** wrote:
> I guess Kmonad only take care of keys but not mouse inputs?

Indeed, there is no mouse support right now and so keyboard + mouse
combinations won't be recognized properly.

**Comment by slotThe** [comment] 2022-03-24 16:05
Closing as a duplicate of #150

**Closed by slotThe** 2022-03-24 16:05 UTC
