### ISSUE TITLE
Not available under this OS  - DeviceSource macOS Monterey M1

### ISSUE THREAD

**Issue by Randalix** [kmonad/kmonad#481] opened 2022-02-10 16:28 UTC
When I try to run kmonad I get `Not available under this OS`

When building with stack on macOS Monterey (Version 12.2), it builds but I get the following error:

```
/Users/joe/repos/kmonad/c_src/mac/keyio_mac.hpp:160:39: error:
     warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
        kr = IOServiceGetMatchingServices(kIOMasterPortDefault,
                                          ^~~~~~~~~~~~~~~~~~~~
                                          kIOMainPortDefault
    |
160 |     kr = IOServiceGetMatchingServices(kIOMasterPortDefault,
    |      
```
I run dtex 1.27.0

**Comment by salastro** [comment] 2022-02-10 22:27
> When I try to run kmonad I get `Not available under this OS`

This problem is usually caused by using wrong configuration, [see this](https://github.com/kmonad/kmonad/blob/master/doc/faq.md#q-when-i-run-kmonad-i-get-error-not-available-under-this-os).

**Comment by slotThe** [comment] 2022-03-24 16:12
Yes, the FAQ should resolve this, so I'm closing.  If there are still problems, feel free to chime in again

**Closed by slotThe** 2022-03-24 16:12 UTC
