### ISSUE TITLE
Build failure on MacOS Sequoia

### ISSUE THREAD

**Issue by sooheon** [kmonad/kmonad#885] opened 2024-09-20 03:24 UTC
```
$ stack install

Warning: nix (Nix) 2.23.3 is on the PATH (at /nix/var/nix/profiles/default/bin/nix) but Stack's Nix
         integration is disabled. To mute this message in future, set notify-if-nix-on-path: false in
         Stack's configuration.

kmonad-0.4.3: unregistering (flags changed from
["-fdext","-f-kext","--extra-include-dirs=/Users/sooheon/code/kmonad/c_src/mac/Karabiner-VirtualHIDDevice/dist/include"]
to ["-f-dext","-f-kext"])
kmonad> configure (lib + exe)
Configuring kmonad-0.4.3...
kmonad> build (lib + exe) with ghc-9.6.6
Preprocessing library for kmonad-0.4.3..
Building library for kmonad-0.4.3..
[ 1 of 35] Compiling KMonad.Prelude.Imports

...

[2 of 2] Linking .stack-work/dist/aarch64-osx/ghc-9.6.6/build/kmonad/kmonad [Objects changed]
ld: warning: search path '/usr/local/gfortran/lib' not found
Undefined symbols for architecture arm64:
  "_grab_kb", referenced from:
       in libHSkmonad-0.4.3-1fZVv7QycZ97pjeP2S2kqT.a[34](IOKitSource.o)
       in libHSkmonad-0.4.3-1fZVv7QycZ97pjeP2S2kqT.a[34](IOKitSource.o)
  "_release_kb", referenced from:
       in libHSkmonad-0.4.3-1fZVv7QycZ97pjeP2S2kqT.a[34](IOKitSource.o)
  "_send_key", referenced from:
       in libHSkmonad-0.4.3-1fZVv7QycZ97pjeP2S2kqT.a[35](KextSink.o)
  "_wait_key", referenced from:
       in libHSkmonad-0.4.3-1fZVv7QycZ97pjeP2S2kqT.a[34](IOKitSource.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ghc-9.6.6: `gcc' failed in phase `Linker'. (Exit code: 1)

Error: [S-7282]
       Stack failed to execute the build plan.

       While executing the build plan, Stack encountered the error:

       [S-7011]
       While building package kmonad-0.4.3 (scroll up to its section to see the error) using:
       /Users/sooheon/.stack/setup-exe-cache/aarch64-osx/Cabal-simple_DY68M0FN_3.10.3.0_ghc-9.6.6 --verbose=1 --builddir=.stack-work/dist/aarch64-osx/ghc-9.6.6 build lib:kmonad exe:kmonad --ghc-options " -fdiagnostics-color=always"
       Process exited with code: ExitFailure 1
```

**Comment by sooheon** [comment] 2024-09-20 03:27
```
$ defaults read /Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist CFBundleVersion
5.0.0
```

also tried with 3.1.0 as recommended in #334 , same error.


```
$ systemextensionsctl list
2 extension(s)
--- com.apple.system_extension.driver_extension (Go to 'System Settings > General > Login Items & Extensions > Driver Extensions' to modify these system extension(s))
enabled	active	teamID	bundleID (version)	name	[state]
*	*	G43BCU2T37	org.pqrs.Karabiner-DriverKit-VirtualHIDDevice (1.8.0/1.8.0)	org.pqrs.Karabiner-DriverKit-VirtualHIDDevice	[activated enabled]
```

weird how here the version number shows as 1.8.0, not the 5.0.0 expected.

**Comment by Cardosaum** [comment] 2024-09-24 06:48
Getting the same error. 

```bash
$ defaults read '/Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/Info.plist' CFBundleVersion
4.3.0
```

```bash
$ sw_vers
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93
```

Also tried with 3.1.0 as mentioned above, same error as well. 

```
$ systemextensionsctl list
4 extension(s)
--- com.apple.system_extension.cmio
enabled	active	teamID	bundleID (version)	name	[state]
	*	2MMRE5MTB8	com.obsproject.obs-studio.mac-camera-extension (30.1.2/8576208847)	com.obsproject.obs-studio.mac-camera-extension	[activated waiting for user]
--- com.apple.system_extension.driver_extension
enabled	active	teamID	bundleID (version)	name	[state]
*	*	G43BCU2T37	org.pqrs.Karabiner-DriverKit-VirtualHIDDevice (1.7.0/1.7.0)	org.pqrs.Karabiner-DriverKit-VirtualHIDDevice	[activated enabled]
--- com.apple.system_extension.network_extension
enabled	active	teamID	bundleID (version)	name	[state]
*	*	J6S6Q257EK	ch.protonvpn.mac.WireGuard-Extension (4.4.0/2408011056)	ProtonVPN WireGuard	[activated enabled]
*	*	J6S6Q257EK	ch.protonvpn.mac.OpenVPN-Extension (4.0.0/2310241059)	ProtonVPN OpenVPN	[activated enabled]
```

**Comment by jokesper** [comment] 2024-09-24 09:11
This error is not the important one.
This is simply caused by the cpp part of KMonad being unable to compile and therefore not existing (to link against).
If you scroll further up there should be errors relating to cpp and hpp files.

I recently got the opportunity to try to install KMonad on a Mac and if I remember there were lots of deprecated warnings, which were marked as errors.
A log (at leat from the cpp compilation) would still be useful.

**Comment by jokesper** [comment] 2024-09-24 10:26
Hmmm interesting.
I found something weird in the logs:
KMonad gets compiled against kext even thouch the flags indicated dext (after recompilation -f-dext?)...
If I remember correctly dext is for macos > 12.0.

**Comment by Cardosaum** [comment] 2024-09-24 10:54
Yeah in the [documentation](https://github.com/kmonad/kmonad/blob/master/doc/installation.md#macos) it's mentioned that kext would be for Catalina and prior only, not sure why `kext` is present in the logs - good catch!

**Comment by stefanerwinmayer** [comment] 2024-09-25 18:45
I'm getting the same errors on Sonoma by simply following the instructions here: https://github.com/kmonad/kmonad/blob/master/doc/installation.md#installing-the-dext

I'm using
`stack build --flag kmonad:dext --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include`
followed by
`stack install`

**Comment by jokesper** [comment] 2024-09-25 18:49
Can you specify -fdext on stack install too, does this change something?

**Comment by Cardosaum** [comment] 2024-09-26 07:19
Oh! 

Compilation succeeded :) 

You were right in mentioning to add `--flag kmonad:dext` during the install process!

This is what I had to do in order to get the code working on Sonoma (14.6.1): 

[Installation Process](https://html-preview.github.io/?url=https://gist.githubusercontent.com/Cardosaum/a5eb179d09da9a7379d82ea363d60771/raw/b019859b264da158e7d1aa5531f70c5ef01787b0/instructions.html)

Thanks @jokesper!

**Comment by jokesper** [comment] 2024-09-26 08:52
No problem, but thank you for sticking with me to debug this.

Now I just need to make a PR to fix the ifdef
and possibly merge the build and install step.

**Comment by jokesper** [comment] 2024-09-26 09:39
Hey could you try this again but with the following instead of the commented out if statement:
```cpp
#if !defined (MAC_OS_X_VERSION_12_0)
    || defined (MAC_OS_X_VERSION_MAX_ALLOWED) && (MAC_OS_X_VERSION_MAX_ALLOWED < MAC_OS_X_VERSION_12_0)
    #define kIOMainPortDefault kIOMasterPortDefault
#endif
```
also could you change `stack build` to `stack install` but keep the flags and then drop the last `stack install` instruction?

After all I don't want to make a PR with untested code

**Comment by stefanerwinmayer** [comment] 2024-09-26 11:52
I'm not a stack expert and I already did some steps of the install. How can I help to verify the linked fix?
Is doing `stack purge` enough before going through the steps again?

**Comment by jokesper** [comment] 2024-09-26 14:34
I sadly am also not a `stack` expert (or even a stack user).
Though I am a `git` user. So `git clean` should work.
Also I think I fixed the macos built complety.

You could probably delete the entire kmonad folder,
and then clone my fork instead and checkout `fix-macos-build-errors` with `git clone -b fix-macos-build-errors --recursive https://github.com/jokesper/kmonad`

**Comment by Cardosaum** [comment] 2024-09-26 15:06
@jokesper, thank you so much for your effort in helping us!

I tested the code and left a comment at your PR. 

Kmonad is successfully installed :)

**Comment by dovahcrow** [comment] 2024-10-14 05:16
> Can you specify -flag kmonad:dext on stack install too, does this change something?

Worked for me. Note it is `--flag` not `-flag`.

**Comment by jokesper** [comment] 2024-10-14 05:19
Then it was as the log suggested. `stack install` recompiled, since the flags changed. `-flag` was a typo on my part.

**Closed** 2024-10-19 08:10 UTC
